// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-chart': string;
  'category-selection': string;
  'chart-button-active': string;
  'chart-view': string;
  'comparison-close': string;
  'comparison-container': string;
  'comparison-menu-bar': string;
  'entry-selection': string;
  'fade-out': string;
  'header': string;
  'header-active': string;
  'menu-bar-container': string;
  'view-wrapper-collapsed': string;
  'menu-bar-selection': string;
  'search-field': string;
  'slide-in': string;
  'slide-out': string;
  'view-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
